### PR TITLE
Initial Signup Component

### PR DESCRIPTION
**Pull request by pamelaabreu**
What are thoughts on changing the input object in state into an array to then use the array map method to return the JSX form inputs?

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
We talked on Slack a bit: #17 contains all the changes in this PR and then some, so this PR can be closed.

Context if anyone's undecided on GitHub PR practice: it's generally preferable to have commits in one branch (and therefore one single PR), not multiple branches & PRs with one commit each. That way folks can review everything in one place. Otherwise you can get to a bunch of PRs open and it'd be hard to find where to comment on things.

From another perspective - if someone posts feedback on a PR asking to change things, it's nice to see in the same PR once those changes have been made. Then you can mark the conversation as resolved, so it's easy to keep track of which ones have or haven't been. GitHub will even show you which comments are outdated from code being changed. It's very snazzy 🎉

**Comment by JoshuaKGoldberg** [comment]
Example Git commands that work well here:

```shell
git checkout -b my-branch master
git add changed-file-one.js
git commit -m "Changed file one"
git push --set-upstream origin my-branch

git add changed-file-two.js
git commit -m "Changed file two"
git push
```

**Comment by Rupa1216** [comment]
We usually write "git push -u origin my-branch". Is it better to do "git push --set-upstream origin my-branch" instead?

**Comment by JoshuaKGoldberg** [comment]
@Rupa1216 the two are the same. `-u` is short for `--set-upstream`.

Your way is more Git literate than mine 😉 I can never remember what the flags do.

**Pull request closed without merging**
